version: '3'

services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'

  backend:
    image: 'sansiv/rentfurlax-backend:latest'
    ports: 
      - '8000:8000'    

  frontend:
    image: 'sansiv/rentfurlax-frontend:latest'
    ports:
      - '3000:3000'    