# Generated by Django 4.1.13 on 2024-02-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentappusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rentappusers',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
