# Generated by Django 4.1.13 on 2024-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentApp', '0003_alter_rentappusers_email_alter_rentappusers_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='username',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
